### ISSUE TITLE
the integer attribute seems to be sent with a Precision attribute that does not exist

### ISSUE THREAD

**Issue by teowave** [MarcusRisanger/Dataverse-API#30]
the integer attribute seems to be sent with a Precision attribute that does not exist

ERROR [2024-11-09 09:22:29] [main: 608]: Unexpected error: POST request failed: Error identified in Payload provided by the user for Entity :'EntityDefinitions', For more information on this error please follow this help link https://go.microsoft.com/fwlink/?linkid=2195293  ---->  InnerException : Microsoft.Crm.CrmException: Invalid property 'Precision' was found in entity 'Microsoft.Dynamics.CRM.IntegerAttributeMetadata'. ---> Microsoft.OData.ODataException: Does not support untyped value in non-open type.

**Comment by MarcusRisanger** [comment]
Thanks for letting me know @teowave - I will look into it this evening 😊👍🏼

**Comment by MarcusRisanger** [comment]
Try to update to version `1.2.1`, I think this error was due to some copy+pasting when I threw together the metadata definitions. I've not used integer type yet, so this slipped through 🔥  Let me know if you still have issues.

Fun to see others using the package!
